### ISSUE TITLE
Phase 4.2: Simple GitHub Actions Deployment

### ISSUE THREAD

**Issue by willtech3** [willtech3/emoji-smith#117]
### **Objective**
Set up basic CI/CD pipeline for automatic deployment to AWS Lambda.

### **Tasks**
- [ ] Create `.github/workflows/deploy.yml` with:
  - Code quality checks (black, flake8, mypy, bandit)
  - Basic unit tests
  - CDK deployment on merge to main
- [ ] Configure GitHub Secrets for AWS credentials
- [ ] Add basic deployment validation (health check)

### **Simple Pipeline**
```yaml
name: Deploy
on:
  push:
    branches: [main]
jobs:
  test:
    - black --check src/
    - flake8 src/
    - pytest tests/
  deploy:
    - cdk deploy --require-approval never
    - curl $API_URL/health # basic validation
```

### **Acceptance Criteria**
- [ ] Code quality checks run on every PR
- [ ] Deployment triggers automatically on main branch
- [ ] Failed deployments are caught and reported
- [ ] Basic post-deployment validation works

### **Dependencies**
- Requires: #116 (CDK Infrastructure)
