### ISSUE TITLE
Implement Architecture Fitness Functions

### ISSUE THREAD

**Issue by willtech3** [willtech3/emoji-smith#233]
**Type**: Feature  
**Priority**: Medium  
**Estimate**: 2 days
**Part of**: #227

## Description
Add automated tests to prevent future architecture violations and maintain DDD principles.

## Acceptance Criteria
- [ ] Architecture tests for layer dependencies
- [ ] Pre-commit hooks for violation detection
- [ ] CI/CD integration with architecture checks
- [ ] Documentation of architecture rules

## Implementation Tasks
1. Create `tests/architecture/` directory
2. Write tests for dependency rules
3. Add pre-commit configuration
4. Update GitHub Actions workflow
5. Create architecture decision records (ADRs)

## Test Examples
```python
def test_no_infrastructure_imports_in_domain():
    """Domain should not import from infrastructure."""
    domain_files = Path("src/emojismith/domain").rglob("*.py")
    for file in domain_files:
        content = file.read_text()
        assert "from emojismith.infrastructure" not in content

def test_application_imports_only_domain():
    """Application should only import from domain."""
    app_files = Path("src/emojismith/application").rglob("*.py")
    for file in app_files:
        content = file.read_text()
        assert "from emojismith.infrastructure" not in content
```

## Pre-commit Configuration
```yaml
# .pre-commit-config.yaml
- repo: local
  hooks:
    - id: check-architecture
      name: Check Architecture Violations
      entry: python scripts/check_architecture.py
      language: python
      files: \.py$
```
